# Codacy Configuration
# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

exclude_paths:
  - "node_modules/**"
  - "dist/**"
  - "coverage/**"
  - ".storybook-web/**"

engines:
  # Disable Trivy - no Dockerfile/containers in this project
  trivy:
    enabled: false
  # Disable legacy ESLint - project uses flat config (eslint.config.js)
  # which Codacy's built-in ESLint doesn't support
  eslint:
    enabled: false
  eslint-8:
    enabled: false
  # Disable CSS linting - Tailwind CSS handles styling, no standalone CSS to lint
  stylelint:
    enabled: false
  csslint:
    enabled: false
  semgrep:
    exclude_paths:
      # Ignore SHA pinning warning for njsscan-action - we accept the risk
      # Rule: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha
      - ".github/workflows/njsscan.yml"
