# Codacy Configuration
# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

exclude_paths:
  - "node_modules/**"
  - "dist/**"
  - "coverage/**"

engines:
  semgrep:
    exclude_paths:
      # Ignore SHA pinning warning for njsscan-action - we accept the risk
      # Rule: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha
      - ".github/workflows/njsscan.yml"
